[package]
name = "eytukan"
version = "0.0.1"
edition = "2021"
license = "GPL-2.0-or-later"
keywords = ["eyukan"]
categories = ["development-tools",""]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/eytukan"
description = "eytukan"

[dependencies]
